# Build phase
FROM node:20 AS build
WORKDIR /motiv_fe
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Serve phase
FROM nginx:alpine
COPY --from=build /motiv_fe/build /usr/share/nginx/html
# nginx.conf /etc/nginx/conf.d/default.conf


# Optional: override default Nginx config to remove caching
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
